version: 2.1
jobs:
  build-and-test:
    docker:
      - image: alpine:3.15
    steps:
      - checkout # Step 1: Check out the code from the repository
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
 
      - run: 
         name: Run tests
         command: python -m unittest test_app.py
  
workflows:
  main-workflow:
  jobs:
    - build-and-test