# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.10
    steps:
      - checkout # Step 1: Check out the code from the repository
      - run: 
         name: Run tests
         command: python -m unittest test_app.py
  
workflows:
  main-workflow:
    jobs:
      - build-and-test
    triggers:
      - schedule:
          cron: "15 8 * * *"
          filters:
            branches:
              only:
                - main